### ISSUE TITLE
RedHat9.2 exec k8s-driver-manager error

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/k8s-driver-manager#37]
I use `gpu-operator:v23.9.0` to install nvidia gpu driver, but `nvidia-driver-daemonset` pod start after, the machine will kernel crash.

I use GPU car is `Tesla P4`.

os info: `Red Hat9.2`,  kernel version is `5.14.0-284.11.1.el9_2.x86_64`.

machine is install `nouveau` driver, and i use `dmesg` command to look kernel log, found having many error about `nouveau`:
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/5509374d-616d-4842-80f0-99a3cd8053cc">

**Comment by lengrongfu** [comment]
@cdesiniotis Have you seen this error?

**Comment by cdesiniotis** [comment]
@lengrongfu I am not familiar. It is recommended to blacklist nouveau as it can conflict with the nvidia driver.

**Comment by lengrongfu** [comment]
I am using gpu-operator to install the driver. Do I need to manually add nouveau to the blacklist before installing gpu-operator?

**Comment by cdesiniotis** [comment]
> I am using gpu-operator to install the driver. Do I need to manually add nouveau to the blacklist before installing gpu-operator?

This is not a required pre-requisite, but because you are seeing errors from nouveau I recommended that you try blacklisting it. Like you pointing out, we do take care of unloaded in the module.

**Comment by lengrongfu** [comment]
Ok, thanks, i exec blacklist nouveau after, `k8s-driver-manager` can exec success,

**Comment by lengrongfu** [comment]
@cdesiniotis Let's discuss whether it is possible to develop a new feature to add an option to k8s-driver-manager to perform the operation of `blacklist nouveau`

**Comment by cdesiniotis** [comment]
Since blacklisting would require updating the initramfs and rebooting the node, it is not something we would be open to adding to this component. This should be done during infrastructure provisioning.
